name: manual qoqo-qasm cratesio publish

on:
  workflow_dispatch:

jobs:
  deploy_cratesio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: setup cargo
      run: |
        # Authentication at crates.io with HQS organizational token
        cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
        # Publish package
        cargo publish --manifest-path=qoqo_qasm/Cargo.toml
